# Generated by Django 2.2.11 on 2020-04-25 08:46

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='edu_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_plan_doc', models.FileField(upload_to='web/static/docs')),
                ('cource', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='entrance_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_code', models.IntegerField(default=103)),
            ],
        ),
        migrations.CreateModel(
            name='entrance_specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.TextField(default='enter specialization here')),
                ('foto', models.ImageField(default='#', upload_to='web/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='entrance_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(default='enter subject here')),
                ('weigth_coef', models.FloatField(default=0.1)),
                ('min_grade', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='foto_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='web/static/img')),
                ('foto_id', models.IntegerField(default=1)),
                ('name_foto', models.TextField(default='enter short description here', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='library_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='enter first name here')),
                ('last_name', models.TextField(default='enter last name here')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=12)),
                ('lon', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=17)),
                ('aux1', models.CharField(max_length=22)),
                ('aux2', models.CharField(max_length=22)),
                ('aux3', models.CharField(max_length=14)),
                ('longname', models.CharField(max_length=40)),
                ('datetime', models.CharField(max_length=14)),
                ('point_numb', models.BigIntegerField()),
                ('dip', models.BigIntegerField()),
                ('dip_angle', models.BigIntegerField()),
                ('dip_prost', models.BigIntegerField()),
                ('rock', models.CharField(max_length=50)),
                ('point_type', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Points_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_city', models.ImageField(default='#', upload_to='web/static/img')),
                ('city_name', models.CharField(max_length=40)),
                ('admin_name', models.CharField(max_length=42)),
                ('cntry_name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='pointX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.TextField(default='kek')),
                ('main_information', models.TextField(default='Write some information here')),
                ('pointX', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='stucture_cathed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathed_name', models.TextField(max_length=50)),
                ('cathed_name_rus', models.TextField(default='write', max_length=100)),
                ('history', models.TextField()),
                ('foto', models.ImageField(upload_to='web/static/img')),
                ('number', models.CharField(max_length=25)),
                ('description', models.TextField(default='enter desciption here')),
                ('email', models.TextField(default='http')),
            ],
        ),
        migrations.CreateModel(
            name='type_foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_foto', models.TextField()),
                ('data_foto', models.DateField()),
                ('foto_type', models.TextField(default='enter type of foto here')),
            ],
        ),
        migrations.CreateModel(
            name='subject_edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.TextField(default='enter name of subject here')),
                ('code', models.TextField(default='OK 1')),
                ('count_credits', models.IntegerField(default='2')),
                ('form_control', models.TextField(default='Іспит')),
                ('cathed_specialization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.stucture_cathed')),
            ],
        ),
        migrations.CreateModel(
            name='structure_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.TextField(default='enter staff here')),
                ('permission_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='structure_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='name')),
                ('last_name', models.TextField(default='sername')),
                ('foto', models.ImageField(default='#', upload_to='web/static/img')),
                ('short_history', models.TextField(default='history')),
                ('phone_number', models.CharField(max_length=25)),
                ('monography', models.TextField(default='monography')),
                ('step', models.TextField(default='doctor')),
                ('cathed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.stucture_cathed')),
                ('staff_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.structure_staff')),
            ],
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_information', models.TextField()),
                ('foto_logo', models.ImageField(upload_to='web/static/img')),
                ('hyper_link_site', models.TextField(default='http')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='library_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='enter name of the book')),
                ('foto', models.ImageField(default='#', upload_to='web/static/img')),
                ('link_for_download', models.FileField(default='enter hyper link here', upload_to='web/static/docs')),
                ('published_in', models.DateField(default=datetime.date(2020, 4, 25))),
                ('type_of_book', models.TextField(default='enter type of book')),
                ('author_id', models.ManyToManyField(to='web.library_author')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Enter title here')),
                ('image_head', models.ImageField(default='#', upload_to='web/static/img')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('link_facebook', models.TextField(default='Enter link here')),
                ('link_telegram', models.TextField(default='Enter link here')),
                ('link_twitter', models.TextField(default='Enter link here')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='future_conference_anonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20000)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('location', models.TextField(default='/')),
                ('link_facebook', models.TextField(default='Enter link here')),
                ('link_telegram', models.TextField(default='Enter link here')),
                ('link_twitter', models.TextField(default='Enter link here')),
                ('foto', models.ImageField(default='#', upload_to='web/static/img')),
                ('partner_id', models.ManyToManyField(to='web.partner')),
            ],
        ),
        migrations.CreateModel(
            name='foto_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='web/static/img')),
                ('name_foto', models.TextField(default='name_foto')),
                ('foto_id', models.IntegerField(default=1)),
                ('header_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.type_foto')),
            ],
        ),
        migrations.CreateModel(
            name='entrance_specialization_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_education', models.TextField(choices=[('Бакалавр', 'Бакалавр'), ('Магістр', 'Магістр'), ('Молодший спеціаліст', 'Молодший спеціаліст')], default='enter your form of education here', max_length=1000)),
                ('education_level', models.TextField(default='enter your education level here', max_length=1000)),
                ('license', models.IntegerField(default=1)),
                ('payment', models.IntegerField(default=1)),
                ('duration_of_study', models.FloatField(default=1.0)),
                ('short_description', models.TextField(default='Enter description here', max_length=100000)),
                ('code_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.entrance_code')),
                ('edu_plan_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.edu_plan')),
                ('subject_id', models.ManyToManyField(to='web.entrance_subject')),
            ],
        ),
        migrations.AddField(
            model_name='entrance_code',
            name='specialization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.entrance_specialization'),
        ),
        migrations.CreateModel(
            name='edu_prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(default='Українська')),
                ('credit_sum', models.IntegerField(default=240)),
                ('specialization_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.edu_plan')),
                ('subject_edu_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.subject_edu')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Enter title here')),
                ('image_head', models.ImageField(default='#', upload_to='web/static/img')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('link_facebook', models.TextField(default='Enter link here')),
                ('link_telegram', models.TextField(default='Enter link here')),
                ('link_twitter', models.TextField(default='Enter link here')),
                ('header_image', models.ManyToManyField(default=1, to='web.foto_article')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
