# Generated by Django 2.2.8 on 2020-01-30 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.TextField(default='Enter title here'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='header_image',
        ),
        migrations.AddField(
            model_name='articles',
            name='header_image',
            field=models.ManyToManyField(default=1, to='web.foto_article'),
        ),
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 1, 31)),
        ),
    ]
