# Generated by Django 2.2.11 on 2020-04-25 21:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_points_city1'),
    ]

    operations = [
        migrations.CreateModel(
            name='shape_loader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='web/static/gis_data')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Points_city1',
        ),
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 4, 26)),
        ),
    ]
