# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181006_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathed_name', models.CharField(max_length=50)),
                ('cource_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pare', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField()),
                ('roof', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rozklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cource')),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.day')),
                ('pare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pare')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.room')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('first_name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='web/static/img'),
        ),
        migrations.AddField(
            model_name='rozklad',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.subject'),
        ),
        migrations.AddField(
            model_name='rozklad',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.teacher'),
        ),
    ]
