# Generated by Django 2.2.8 on 2020-01-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200131_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto_article',
            name='header_id',
        ),
    ]
