# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190206_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='cathed_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.TextField(max_length=10000),
        ),
    ]
