# Generated by Django 2.2.8 on 2020-02-02 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_foto_article_header_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance_specialization_way',
            name='edu_plan_id',
        ),
        migrations.AddField(
            model_name='entrance_specialization_way',
            name='edu_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.edu_plan'),
        ),
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 2, 3)),
        ),
    ]
