# Generated by Django 2.2.8 on 2020-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200203_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure_person',
            old_name='first_name',
            new_name='last_name',
        ),
    ]
