# Generated by Django 2.2.11 on 2020-04-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_geology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geology',
        ),
    ]
