# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190220_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='cathed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathed_name', models.TextField(max_length=50)),
                ('history', models.TextField()),
                ('foto', models.ImageField(upload_to='web/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='web/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='hyper_link_usefull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('hyper_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_information', models.TextField()),
                ('foto_logo', models.ImageField(upload_to='web/static/img')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='short_history',
            field=models.TextField(default='history'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='cathed_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cathed'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='cource_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pare',
            name='id_pare',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='roof',
            field=models.IntegerField(default=301),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cathed_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.cathed'),
            preserve_default=False,
        ),
    ]
