# Generated by Django 2.2.8 on 2020-02-07 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200203_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link_facebook',
            field=models.TextField(default='Enter link here'),
        ),
        migrations.AddField(
            model_name='articles',
            name='link_telegram',
            field=models.TextField(default='Enter link here'),
        ),
        migrations.AddField(
            model_name='articles',
            name='link_twitter',
            field=models.TextField(default='Enter link here'),
        ),
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 2, 7)),
        ),
    ]
