# Generated by Django 2.2.8 on 2020-02-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200207_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='future_conference_anonce',
            name='link_facebook',
            field=models.TextField(default='Enter link here'),
        ),
        migrations.AddField(
            model_name='future_conference_anonce',
            name='link_telegram',
            field=models.TextField(default='Enter link here'),
        ),
        migrations.AddField(
            model_name='future_conference_anonce',
            name='link_twitter',
            field=models.TextField(default='Enter link here'),
        ),
    ]
