# Generated by Django 2.2.11 on 2020-04-27 12:03

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_geology'),
    ]

    operations = [
        migrations.CreateModel(
            name='geol_raster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#', max_length=30)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 4, 27)),
        ),
    ]
