# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190319_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_foto', models.TextField()),
                ('data_foto', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='foto_id',
            field=models.ImageField(default=1, upload_to=b''),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name_foto',
            field=models.TextField(default='name_foto'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='header_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.type_foto'),
        ),
    ]
