# Generated by Django 2.2.8 on 2020-03-09 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 3, 9)),
        ),
        migrations.AlterField(
            model_name='structure_person',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='stucture_cathed',
            name='number',
            field=models.CharField(max_length=13),
        ),
    ]
