# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190320_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='y',
            field=models.IntegerField(default=1),
        ),
    ]
