# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_day_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='y',
        ),
        migrations.AlterField(
            model_name='rozklad',
            name='cource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cathed'),
        ),
    ]
