# Generated by Django 2.2.8 on 2020-03-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200309_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure_person',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stucture_cathed',
            name='number',
            field=models.CharField(max_length=25),
        ),
    ]
