# Generated by Django 2.2.11 on 2020-03-14 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200309_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_book',
            name='published_in',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
    ]
