# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190320_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozklad',
            name='cource_id',
        ),
        migrations.AddField(
            model_name='rozklad',
            name='cathed_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.cathed'),
        ),
    ]
