# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190320_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='hyper_link_site',
            field=models.TextField(default='http'),
        ),
    ]
