# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190330_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathed',
            name='cathed_name_rus',
            field=models.TextField(default='write', max_length=100),
        ),
    ]
