# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-31 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_cathed_cathed_name_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozklad',
            name='cathed_id',
            field=models.TextField(default='geology'),
        ),
    ]
