# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190523_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='monography',
            field=models.TextField(default='monography'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
