# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190523_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='step',
            field=models.TextField(default='doctor'),
        ),
    ]
