# Generated by Django 2.2.1 on 2019-06-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_teacher_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonce',
            name='user',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
    ]
